from typing import Any, Mapping, Optional, Protocol

class QueryResult(Protocol):
    data: Any
    count: int | None

class TableQuery(Protocol):
    def select(self, *args: Any, **kwargs: Any) -> "TableQuery": ...
    def eq(self, *args: Any, **kwargs: Any) -> "TableQuery": ...
    def gt(self, *args: Any, **kwargs: Any) -> "TableQuery": ...
    def gte(self, *args: Any, **kwargs: Any) -> "TableQuery": ...
    def lt(self, *args: Any, **kwargs: Any) -> "TableQuery": ...
    def in_(self, *args: Any, **kwargs: Any) -> "TableQuery": ...
    def order(self, *args: Any, **kwargs: Any) -> "TableQuery": ...
    def limit(self, *args: Any, **kwargs: Any) -> "TableQuery": ...
    def maybe_single(self) -> "TableQuery": ...
    def insert(self, *args: Any, **kwargs: Any) -> "TableQuery": ...
    def update(self, *args: Any, **kwargs: Any) -> "TableQuery": ...
    def delete(self) -> "TableQuery": ...
    def execute(self) -> QueryResult: ...

class RpcQuery(Protocol):
    def execute(self) -> QueryResult: ...

class StorageBucket(Protocol):
    def upload(self, *args: Any, **kwargs: Any) -> Any: ...
    def download(self, *args: Any, **kwargs: Any) -> Any: ...
    def list(self, *args: Any, **kwargs: Any) -> Any: ...

class StorageClient(Protocol):
    def list_buckets(self) -> Any: ...
    def from_(self, name: str) -> StorageBucket: ...

class Client(Protocol):
    storage: StorageClient
    auth: Any
    postgrest: Any
    def table(self, name: str) -> TableQuery: ...
    def rpc(self, fn: str, params: Optional[Mapping[str, Any]] = ...) -> RpcQuery: ...


def create_client(url: str, key: str) -> Client: ...
